import json
import anthropic
from dotenv import load_dotenv
from src.models import TranscriptSegment, Topic, Summary, SummarySegment
from src.config import LLM_MODEL

load_dotenv()
client = anthropic.Anthropic()


# ---------------------------------------------------------------------------
# 1. link_evidence
# ---------------------------------------------------------------------------

def link_evidence(
    summary: Summary,
    segments: list[TranscriptSegment],
    topics: list[Topic],
) -> Summary:
    """
    Break the summary into individual paragraphs and link each one back to
    the source transcript segments it was derived from.

    The summary as generated by summarizers.py stores one SummarySegment per
    topic, all sharing the same full text — it's coarse-grained traceability.
    This function produces fine-grained traceability: one SummarySegment per
    *paragraph*, each tagged with the topic it discusses and the source
    segment indices for that topic.

    Steps:
    1. Split the summary text into paragraphs.
    2. Ask Claude which topic each paragraph belongs to (one API call).
    3. Look up that topic's segment_indices.
    4. Return a new Summary with one SummarySegment per paragraph.
    """

    # --- Step 1: split summary text into paragraphs ---
    # The summary is stored identically across all SummarySegments, so [0] is fine.
    full_text = summary.segments[0].text
    paragraphs = [p.strip() for p in full_text.split("\n\n") if p.strip()]

    if not paragraphs:
        # Nothing to link — return the original summary unchanged.
        return summary

    # --- Step 2: ask Claude to classify each paragraph by topic ---
    topic_names = ", ".join(t.name for t in topics)

    # Number each paragraph so Claude's response can reference them by index.
    numbered_paragraphs = "\n\n".join(
        f"{i}. {para}" for i, para in enumerate(paragraphs)
    )

    prompt = (
        f"Here are the topics: {topic_names}.\n\n"
        f"For each numbered paragraph below, identify which topic it discusses. "
        f"Return ONLY a JSON array of objects with 'paragraph_index' (int) and "
        f"'topic_name' (str). No other text.\n\n"
        f"{numbered_paragraphs}"
    )

    try:
        response = client.messages.create(
            model=LLM_MODEL,
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.content[0].text.strip()
    except Exception as e:
        raise RuntimeError(f"API call failed in link_evidence: {e}") from e

    # Strip accidental markdown fences before parsing.
    raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    try:
        classifications = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Could not parse evidence JSON from Claude:\n{raw}\nError: {e}"
        ) from e

    # --- Step 3: build a topic lookup for fast access ---
    # Maps topic_name → Topic object so we can grab segment_indices quickly.
    topic_map = {t.name: t for t in topics}

    # Build a classification lookup: paragraph_index → topic_name.
    para_to_topic = {item["paragraph_index"]: item["topic_name"] for item in classifications}

    # --- Step 4: build fine-grained SummarySegment objects ---
    new_segments = []
    for i, para_text in enumerate(paragraphs):
        topic_name = para_to_topic.get(i, topics[0].name)   # fall back to first topic if missing
        topic = topic_map.get(topic_name, topics[0])

        new_segments.append(SummarySegment(
            text=para_text,
            topic_name=topic_name,
            source_segment_indices=topic.segment_indices,
        ))

    # Return a new Summary — same type and metadata, but with paragraph-level segments.
    updated_metadata = {**summary.metadata, "evidence_linked": True}
    return Summary(
        segments=new_segments,
        summary_type=summary.summary_type,
        metadata=updated_metadata,
    )


# ---------------------------------------------------------------------------
# 2. format_evidence_report
# ---------------------------------------------------------------------------

def format_evidence_report(
    summary: Summary,
    segments: list[TranscriptSegment],
) -> str:
    """
    Build a human-readable report showing each summary paragraph alongside
    the raw transcript excerpts it was derived from.

    For each SummarySegment:
    - Print the summary paragraph.
    - Print up to 2 source segment excerpts (first 100 words each) as evidence.

    This lets a reader verify that every claim in the summary is grounded in
    the actual transcript.
    """
    lines = []
    lines.append("=" * 70)
    lines.append("EVIDENCE REPORT")
    lines.append(f"Summary type: {summary.summary_type}")
    lines.append("=" * 70)

    for i, seg in enumerate(summary.segments):
        lines.append(f"\n[Paragraph {i + 1}] Topic: {seg.topic_name}")
        lines.append("-" * 50)
        lines.append(seg.text)
        lines.append("\nEvidence from transcript:")

        # Take up to 2 source segments to keep the report readable.
        evidence_indices = seg.source_segment_indices[:2]

        if not evidence_indices:
            lines.append("  (no source segments linked)")
        else:
            for idx in evidence_indices:
                source = segments[idx]
                # First 100 words of the source segment.
                excerpt = " ".join(source.text.split()[:100])
                lines.append(f"  [Segment {idx}]: \"{excerpt}...\"")

        lines.append("")   # blank line between paragraphs

    lines.append("=" * 70)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from src.loader import load_transcript
    from src.segmenter import segment_transcript
    from src.preferences import create_preferences
    from src.summarizers import generate_constrained_summary

    segments = load_transcript("data/transcripts/episode1.txt")
    topics = segment_transcript(segments)

    # Hardcoded test ratings: first 2 high, next 3 medium, rest low.
    test_ratings = {}
    for i, topic in enumerate(topics):
        if i < 2:
            test_ratings[topic.name] = "high"
        elif i < 5:
            test_ratings[topic.name] = "medium"
        else:
            test_ratings[topic.name] = "low"

    preferences = create_preferences(topics, test_ratings)

    print("\nGenerating constrained summary...")
    summary = generate_constrained_summary(segments, topics, preferences)

    print("Linking evidence to paragraphs...")
    linked_summary = link_evidence(summary, segments, topics)

    print(f"\nLinked {len(linked_summary.segments)} paragraphs to source segments.\n")

    report = format_evidence_report(linked_summary, segments)
    print(report)
